service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

	
plugins:
  - serverless-webpack
  	
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'

functions:
  getProductsList:
    handler: handlers/getProductsList.getProductsList
    events:
      - http:
          method: "get"
          path: "products"
          cors: true
                  
  getProductById:
    handler: handlers/getProductById.getProductById
    events:
      - http:
          method: "get"
          path: "products/{id}"
          cors: true
