service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

  environment:
    SNS_ARN:
      Ref: createProductTopic

  iamRoleStatements:
    - Effect: "Allow"
      Action: "sns:*"
      Resource:
        Ref: createProductTopic

resources:
  Resources:
    catalogItemsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    createProductTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: epsergeibolonikov@gmail.com
        Protocol: email
        TopicArn:
          Ref: createProductTopic
    SNSSubscriptionFiltered:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: sergeibolonikov@gmail.com
        Protocol: email
        TopicArn:
          Ref: createProductTopic
        FilterPolicy:
          type: 
            - filter


	
plugins:
  - serverless-webpack
  	
package:
  individually: true
  	
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'

functions:
  getProductsList:
    handler: handlers/getProductsList.getProductsList
    events:
      - http:
          method: "get"
          path: "products"
          cors: true
                  
  getProductById:
    handler: handlers/getProductById.getProductById
    events:
      - http:
          method: "get"
          path: "products/{id}"
          cors: true

  createProduct:
    handler: handlers/createProduct.createProduct
    events:
      - http:
          method: "post"
          path: "products"
          cors: true

  catalogBatchProcess:
    handler: handlers/catalogBatchProcess.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - catalogItemsQueue
              - Arn
