service: authorization-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1

plugins:
  - serverless-dotenv-plugin

functions:
  basicAuthorizer:
    handler: handlers/basicAuthorizer.basicAuthorizer
